baseURL = "https://feed-dead-beef.netlify.com/"
languageCode = "en-us"
title = "feed dead beef"
theme = "hermit"

pygmentsCodeFences = true
pygmentsUseClasses = true

[taxonomies]
  series = "series"
  tag = "tags"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  gitUrl = "https://github.com/detunized/blog"

  [[params.social]]
    name = "github"
    url = "https://github.com/detunized"

  [[params.social]]
    name = "telegram"
    url = "http://t.me/detunized"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/dmitryyakimenko"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/detunized_net"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 10

  [[menu.main]]
    name = "Photo"
    url = "/photo/"
    weight = 20

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 30
