baseURL = "https://detunized.net/"
languageCode = "en-us"
title = "0xDEADBEEF"
theme = "hermit"

pygmentsCodeFences = true
pygmentsUseClasses = true

[taxonomies]
  series = "series"
  tag = "tags"

[permalinks]
  posts = "/posts/:year-:month-:day-:slug"
  photo = "/photo/:slug"

[params]
  author = "Dmitry Yakimenko"
  email = "detunized@gmail.com"

  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  gitUrl = "https://github.com/detunized/blog"

  imageHost = "https://raw.seedhost.eu/detunized/detunized.net"

  [params.photo]
    paginate = 12
    url = "/photo/"

  [[params.social]]
    name = "github"
    url = "https://github.com/detunized"

  [[params.social]]
    name = "telegram"
    url = "http://t.me/detunized"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/dmitryyakimenko"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/detunized_net"

  [[params.social]]
    name = "dev"
    url = "https://dev.to/detunized"

  [[params.social]]
    name = "medium"
    url = "https://medium.com/@detunized"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    name = "Photo"
    url = "/photo/"
    weight = 20

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 30
