baseURL: "https://detunized.net/"
languageCode: "en-us"
title: "0xDEADBEEF"
theme: "hermit"
googleAnalytics: "G-SHWZN6VT5J"

pygmentsCodeFences: true
pygmentsUseClasses: true

taxonomies:
  series: "series"
  tag: "tags"

permalinks:
  posts: "/posts/:year-:month-:day-:slug"
  photo: "/photo/:slug"
  games: "/games/:slug"

params:
  author: "Dmitry Yakimenko"
  email: "detunized@gmail.com"
  dateform: "Jan 2, 2006"
  dateformShort: "Jan 2"
  dateformNum: "2006-01-02"
  dateformNumTime: "2006-01-02 15:04"
  gitUrl: "https://github.com/detunized/blog/commit/"
  imageHost: "https://raw.seedhost.eu/detunized/detunized.net"

  photo:
    paginate: 12
    url: "/photo/"

  social:
    - name: "github"
      url: "https://github.com/detunized"
    - name: "telegram"
      url: "http://t.me/detunized"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/dmitryyakimenko"
    - name: "twitter"
      url: "https://twitter.com/detunized_net"
    - name: "dev"
      url: "https://dev.to/detunized"
    - name: "medium"
      url: "https://medium.com/@detunized"

menu:
  main:
    - name: "Blog"
      url: "/posts/"
      weight: 10
    - name: "Photo"
      url: "/photo/"
      weight: 20
    - name: "Games"
      url: "/games/"
      weight: 30
    - name: "About"
      url: "/about/"
      weight: 40

module:
  imports:
    - path: "github.com/detunized/lung-pong"
      mounts:
        - source: "index.html"
          target: "content/games/01-lung-pong/game.html"
        - source: "game.js"
          target: "content/games/01-lung-pong/game.js"
